version: '3.8'

services:
  backend:
    build: .
    image: backend-backend
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    command: "./main"

  waha:
    image: devlikeapro/waha-plus:chrome
    ports:
      - "3001:3000"
    environment:
      - WAHA_WEBHOOK_URL=http://159.65.34.199:8081/api/webhook/whatsapp
    restart: unless-stopped
